### ISSUE TITLE
Opened index.html

### ISSUE THREAD

**Issue by null15** [TJEEPOT/Palia-Checklists#1]
There is no content, is it because its WIP?

**Comment by TJEEPOT** [comment]
I honestly had not expected someone to be looking at the site within an hour of the project going live, lol. Yeah, it's brand new, still working on the most basic features. I might have a sortable table in basic HTML working in the next couple of hours.

**Comment by null15** [comment]
> I honestly had not expected someone to be looking at the site within an hour of the project going live, lol. Yeah, it's brand new, still working on the most basic features. I might have a sortable table in basic HTML working in the next couple of hours.

Sweet, looking forward to great progress on the project! :)

Well, Palia is very trendy and famous lately, so someone already checking out your project already shouldn't be a surprise :D

I'm lvl 180 ingame so I'm quite knowledgeable on the game so if you need any tips or ideas on what to make, you can try asking me. :)

**Comment by TJEEPOT** [comment]
Thanks for the offer, I'll be sure to keep it in mind! 

It took a little while but the alpha version of the fishing tool just went live - it's been a bit of a nightmare since I've never really used much JS before, so that's been a learning curve on top of wrangling how to store data behind-the-scenes on each row and figuring out how to make separate logic for hiding different lines.

I'll be making it a bit nicer to look at and use over the week when I have the time, as well as add a tracking system for keeping track of fish already caught. Updates will probably be slower than I'd like, but if there's anything you would like to see when using it, let me know and I'll see what I can do.

**Comment by null15** [comment]
> Thanks for the offer, I'll be sure to keep it in mind!
> 
> It took a little while but the alpha version of the fishing tool just went live - it's been a bit of a nightmare since I've never really used much JS before, so that's been a learning curve on top of wrangling how to store data behind-the-scenes on each row and figuring out how to make separate logic for hiding different lines.
> 
> I'll be making it a bit nicer to look at and use over the week when I have the time, as well as add a tracking system for keeping track of fish already caught. Updates will probably be slower than I'd like, but if there's anything you would like to see when using it, let me know and I'll see what I can do.

Thanks! Will be giving it a try and I'll let you know <3
